name: Hprofile Actions
on: [workflow_dispatch]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Maven Test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Set Java 11 
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup SonarQube
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        with:
            projectBaseDir: src/
            args: >
              -Dsonar.host.url=${{ secrets.SONAR_URL }}
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
              -Dsonar.organization=${{ secrets.SONAR_ORG }}
              -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
              -Dsonar.junit.reportsPath=target/surefire-reports/ 
              -Dsonar.jacoco.reportsPath=target/jacoco.exec 
              -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
              -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/
